### ISSUE TITLE
KVM support

### ISSUE THREAD

**Issue by ghost** [limboemu/limbo#11] opened 2016-07-08 16:48 UTC
It would be good to add you KVM, for smartphones such as zenfone 2 having processors Intel x64 emulation and faster.

**Comment by limboemu** [comment] 2016-07-11 08:31
There are a few caveats about KVM support in qemu.

Qemu:
1) Requires KVM header files, let's assume I've got these right.
2) Seems..? it requires POSIX shared memory (ivshmem.c: open_shm) which is not supported in Android. There is ashmem available but only in the form of MemoryFile in Java (not in NDK). Now what is really required is the file descriptor which we could theorize one could get it via Java reflection (not ideal) and pass it to qemu during run time via JNI.
3) I currently do not have an x86 device to test with. One would need to root & flash a KVM compatible kernel and iteratively work any incompatibility bugs which is I safely say is a little overwhelming right now.

Let's leave this request open and see if anyone can help.

**Comment by limboemu** [comment] 2016-07-11 08:37
Additional literature:
http://linux.die.net/man/3/shm_open
http://stackoverflow.com/questions/23202366/android-ndk-shared-memory-how-to-use-ashmem-create-region
https://vec.io/posts/andriod-ipc-shared-memory-with-ashmem-memoryfile-and-binder

**Comment by limboemu** [comment] 2016-07-11 08:45
On second thought it seems the Virtual PCI Device that uses the shared memory is optional and might not be required.
-device ivshmem

**Comment by limboemu** [comment] 2016-07-11 14:02
I added the changes for supporting KVM in 69f48cd.
If you have an x86 phone with KVM and you want to try it out let me know and I can build a snapshot version for you.

**Comment by AndrewAVX** [comment] 2016-07-22 20:41
Hello! I've got a Zenfone 2 ZE551ML (x86_64-device) with KVM modules. I want get a build of Limbo Emulator with KVM support. How can I contact you for more details?

**Comment by limboemu** [comment] 2016-07-24 17:45
Thanks for your offer, I think I have a snapshot version ready. I'll add a link you can download it from.

**Comment by limboemu** [comment] 2016-07-24 18:37
[limbo-android-snapshot-07042016-debug-x86-kvmenabled.zip](https://github.com/limboemu/limbo/files/380429/limbo-android-snapshot-07042016-debug-x86-kvmenabled.zip)

**Comment by limboemu** [comment] 2016-07-25 09:04
From issue #30 
https://www.youtube.com/watch?v=5iDLZ87yitU
[logcat.txt](https://github.com/limboemu/limbo/files/381083/logcat.txt)

**Comment by limboemu** [comment] 2016-07-25 09:13
@AndrewAVX 
Thanks for the logcat the only thing that stands out is the error by touchboostpulse. Not sure if this is related.

Can you please  provide a dmesg output?
Also, try the following:
a. make sure that /dev/kvm has appropriate permissions given to the uid of the Android app (limbo).
b. try using the "kvm64" cpu.

**Comment by AndrewAVX** [comment] 2016-07-25 20:02
1) [dmesg.txt](https://github.com/limboemu/limbo/files/382354/dmesg.txt)
2) Is it right?
root@Z00A:/ # ls -l /dev/kvm
crwxrwxrwx u0_a163  u0_a163   10, 232 2016-07-25 04:07 kvm
3) "kvm64" CPU + "Enable KVM" not working too.

**Comment by AndrewAVX** [comment] 2016-07-28 00:43
Hello! I have found what the problem with Limbo starting with -enable-kvm. The problem is not in the source code of Limbo, a problem with the rights of /dev/kvm on my phone.
ls -l /dev/kvm
On my PC:
andrew@andrew: ~ $ ls -l /dev/kvm
crw-rw ---- + 1 root kvm 10, 232 July 28 02:19 /dev/kvm
On my phone:
root@Z00A: / # ls -l /dev/kvm
crw-rw ---- root root 10 2016-07-28 02:22 kvm 232

As can be seen, on the PC shown «root kvm», the phone «root root». This is the problem with the KVM starting in Limbo.

If I run the command «chown root: kvm /dev /kvm», it is be a mistake:
«chown: kvm: invalid group name»
I do not know how to create a group «kvm» in my device.

But I think I know the solution! root-mode in Limbo! I think if you add in Limbo run as root, you will not have problems with the launch of a virtual machine with the -enable-kvm.

**Comment by limboemu** [comment] 2016-08-30 15:25
I'm afraid I don't have an answer for this yet.

**Comment by evg-zhabotinsky** [comment] 2017-01-11 17:41
Did you try `chmod 555`, by the way?

**Comment by Mynzer** [comment] 2017-03-01 21:51
Hi. I'm another Zenfone 2 ZE551ML user with KVM modules.

I'm using limbo-android-x86-kvm-2.4.0.alpha.apk
I've tried the following things

- View my current userId of limbo app
root@Z00A_1:/ # dumpsys package com.limbo.emu.main | grep userId           
    userId=10146 gids=[3003, 1028, 1015]

- I've change the user group of /dev/kvm from root:root to root:u0_a146
a then chmod 666, ending like this
root@Z00A_1:/ # ls -l /dev/kvm
crw-rw-rw- root     u0_a146   10, 232 2017-03-01 11:50 kvm

- Select "kvm64" in cpu settings

But when I start limbo with the option "Enable KVM", I get exactly the same
result from the youtube video posted before

I can help in testing too, and maybe testing a limbo version with root-mode

**Comment by tjg1** [comment] 2017-03-04 21:36
If you don't have an x86 device, I recommend testing it with [Remix OS](http://www.jide.com/remixos). 

Being able to run "real" Linux in a VM would make it a lot more attractive as a main OS for software developers.

**Comment by erenoglu** [comment] 2017-03-14 14:25
In my view the main power will come when we can run Remix OS or Phoenix OS on the PC and have Windows 10 in limbo when we need to run some specific app (ie Excel with pivot tables). 
This will open lots of possibilities.

**Comment by ycavan** [comment] 2017-04-10 15:49
Using my kvm-enabled kernel on the Asus Zenfone 2, I'm getting similar issues as the other guys.  I see that there's no Android window for SDL when kvm is enabled.  no text or anything, just a black screen.  Without kvm, everything boots like normal.

When I run qemu from my Arch linux chroot on the same phone, I mark the qemu binaries w/ a+s to run qemu-system-x86_64 as root.  Here's how I start up the windows 10 VM on my arch linux chroot:

qemu-system-x86_64 -full-screen -m 1G -enable-kvm -cpu host -drive file=/mnt/0/machine2.img,format=qcow2 -boot menu=on -smp sockets=2,cores=1,threads=1 -vga qxl -monitor stdio -balloon virtio -soundhw hda -net nic,model=virtio -net use,smb=/mnt/MicroSD,hostfwd=tcp::5555-:3389 -k en-us -usb -device usb-ehci,id=ehci --usbdevice tablet -spice port=5900,disable-ticketing

I notice in the logcat, that the parameters you're using are different ( obviously ), but what puzzles me is the CPU type.  w/ kvm, you want cpu=host so qemu pulls the cpu information directly from the host cpu.

Would it be possible to compile qemu as a command line application?  if so, then you could open up a shell and execute it as root w/ the appropriate switches.  It would also be nice to have an "expert" option to type in our own command line switches.

Anyway, hope the following information helps in figuring out what's going on with your build & kvm.

Modules:

1|root@Z00A:/ # lsmod
lsmod
dfrgx 13845 0 - Live 0x0000000000000000
bcmdhd 635276 0 - Live 0x0000000000000000
cfg80211 447523 1 bcmdhd, Live 0x0000000000000000
llc 5580 0 - Live 0x0000000000000000
vringh 13904 0 - Live 0x0000000000000000
vhost_net 30116 0 - Live 0x0000000000000000
virtio_net 21199 0 - Live 0x0000000000000000
virtio_console 20945 0 - Live 0x0000000000000000
virtio_balloon 6122 0 - Live 0x0000000000000000
virtio_pci 7633 0 - Live 0x0000000000000000
virtio_mmio 7028 0 - Live 0x0000000000000000
kvm_intel 132177 0 - Live 0x0000000000000000
kvm 414421 1 kvm_intel, Live 0x0000000000000000
atomisp_css2401a0_v21 740036 0 - Live 0x0000000000000000
sky81296 13525 1 - Live 0x0000000000000000
ov5670 35733 1 - Live 0x0000000000000000
m10mo_spi 3674 0 - Live 0x0000000000000000
m10mo_isp 123701 2 atomisp_css2401a0_v21,m10mo_spi, Live 0x0000000000000000
t4k37 43556 1 - Live 0x0000000000000000
libmsrlisthelper 2434 1 t4k37, Live 0x0000000000000000
rmi4 36439 0 - Live 0x0000000000000000
bcm_bt_lpm 8006 0 - Live 0x0000000000000000
videobuf_vmalloc 5125 1 atomisp_css2401a0_v21, Live 0x0000000000000000
videobuf_core 19926 2 atomisp_css2401a0_v21,videobuf_vmalloc, Live 0x00000000000
00000
fps_throttle 3096 0 - Live 0x0000000000000000
tngdisp 1282443 147 dfrgx, Live 0x0000000000000000

/dev/kvm is in the same group as the app:
root@Z00A:/ # ls -l /dev/kvm
ls -l /dev/kvm
crw-rw---- root     u0_a257   10, 232 2017-04-10 07:54 kvm
root@Z00A:/ #

Logcat:
I/ActivityManager(  690): START u0 {act=android.intent.action.MAIN cat=[android.
intent.category.LAUNCHER] flg=0x10200000 cmp=com.limbo.emu.main/.LimboEmuActivit
y bnds=[303,1229][540,1551] (has extras)} from uid 10013 on display 0
V/ActivityManager(  690): Displayed ActivityRecord{21330792 u0 com.limbo.emu.mai
n/.LimboEmuActivity t26786} Resume. Not First Launch.
D/LauncherLog( 1265): Launcher:: startActivity: pkg: com.limbo.emu.main clz: com
.limbo.emu.main.LimboEmuActivity
D/PowerSaverService( 3170): current package:com.limbo.emu.main;activity:com.limb
o.emu.main.LimboEmuActivity
I/ActivityManager(  690): Displayed com.limbo.emu.main/.LimboEmuActivity: +114ms

W/LinkRimService( 1025): ---app importance: 100appProcess.processName: com.limbo
.emu.main
V/VMExecutor(12608): Found packageName: com.limbo.emu.main
V/VMExecutor(12608): Found dataDir: /data/data/com.limbo.emu.main
I/ActivityManager(  690): START u0 {cmp=com.limbo.emu.main/com.max2idea.android.
limbo.main.LimboSDLActivity} from uid 10257 on display 0
V/Monotype(12608): SetAppTypeFace- try to flip, app = com.limbo.emu.main
E/C:/users/dev/limbo/limbo-android/jni/..//jni/SDL/src/video/android/SDL_android
touch.c:99(12608): No Android Window!
E/C:/users/dev/limbo/limbo-android/jni/..//jni/SDL/src/video/android/SDL_android
touch.c:99(12608): No Android Window!
I/ActivityManager(  690): Displayed com.limbo.emu.main/com.max2idea.android.limb
o.main.LimboSDLActivity: +266ms
D/StatusBar(  872): onNotificationPosted: StatusBarNotification(pkg=com.limbo.em
u.main user=UserHandle{0} id=1000 tag=null score=0 key=0|com.limbo.emu.main|1000
|null|10257: Notification(pri=0 contentView=com.limbo.emu.main/0x1090095 vibrate
=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PRIVATE))
D/PhoneStatusBar(  872): addNotification key=0|com.limbo.emu.main|1000|null|1025
7
I/C:/users/dev/limbo/limbo-android/jni/..//jni/SDL/src/core/android/SDL_android.
c:97(12608): JNI_OnLoad called
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:387(12608
): ***************** INIT LIMBO ************************
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:398(12608
): CPU= kvm64
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:406(12608
): Machine Type= pc
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:411(12608
): MEM= 128
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:416(12608
): CPU Num= 1
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:442(12608
): vnc_allow_external= 0
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:447(12608
): disablefdbootchk= 0
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:454(12608
): Keyboard Layout = en-us
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:461(12608
): HDA= (null)
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:504(12608
): SD= (null)
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:513(12608
): Shared Folder= (null)
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:642(12608
): Finished getting Java fields
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:651(12608
): Setting Params
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:759(12608
): Adding vga: std
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:771(12608
): Adding Net: none
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:862(12608
): Enable qmp server
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:912(12608
): Disabling VNC server, using SDL instead
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:924(12608
): Setting multi core: 1
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:928(12608
): Setting machine type: pc
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:932(12608
): Setting tb memory
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:936(12608
): Setting real time
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:940(12608
): Setting clock
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:967(12608
): Preparing args param=27
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[0]=/data/data/com.limbo.emu.main/lib/libqemu-system-x86_64.so
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[1]=-cpu
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[2]=kvm64
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[3]=-m
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[4]=128
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[5]=-L
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[6]=/storage/emulated/0/limbo/
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[7]=-vga
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[8]=std
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[9]=-net
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[10]=none
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[11]=-qmp
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[12]=tcp:localhost:4444,server,nowait
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[13]=-enable-kvm
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[14]=-k
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[15]=en-us
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[16]=-smp
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[17]=1
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[18]=-M
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[19]=pc
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[20]=-tb-size
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[21]=32M
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[22]=-realtime
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[23]=mlock=off
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[24]=-rtc
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[25]=base=localtime
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:976(12608
): param[26]=-localtime
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:983(12608
): ***************** INIT QEMU ************************
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:985(12608
): Starting VM...
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:47(12608)
: Loading lib: /data/data/com.limbo.emu.main/lib/libqemu-system-x86_64.so
V/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:1009(1260
8): Loading symbol qemu_start...
D/vl.c:3362(12608): Storing limbo_base_dir=/storage/emulated/0/limbo/
D/PowerSaverService( 3170): current package:com.limbo.emu.main;activity:com.max2
idea.android.limbo.main.LimboSDLActivity
W/LinkRimService( 1025): ---app importance: 100appProcess.processName: com.limbo
.emu.main
W/LinkRimService( 1025): ---app importance: 100appProcess.processName: com.limbo
.emu.main
W/LinkRimService( 1025): ---app importance: 100appProcess.processName: com.limbo
.emu.main
W/LinkRimService( 1025): ---app importance: 100appProcess.processName: com.limbo
.emu.main
W/LinkRimService( 1025): ---app importance: 100appProcess.processName: com.limbo
.emu.main
W/InputDispatcher(  690): channel '30f74e25 com.limbo.emu.main/com.limbo.emu.mai
n.LimboEmuActivity (server)' ~ Consumer closed input channel or an error occurre
d.  events=0x9
E/InputDispatcher(  690): channel '30f74e25 com.limbo.emu.main/com.limbo.emu.mai
n.LimboEmuActivity (server)' ~ Channel is unrecoverably broken and will be dispo
sed!
I/WindowState(  690): WIN DEATH: Window{30f74e25 u0 com.limbo.emu.main/com.limbo
.emu.main.LimboEmuActivity}
W/InputDispatcher(  690): Attempted to unregister already unregistered input cha
nnel '30f74e25 com.limbo.emu.main/com.limbo.emu.main.LimboEmuActivity (server)'
I/WindowState(  690): WIN DEATH: Window{15f9a233 u0 com.limbo.emu.main/com.max2i
dea.android.limbo.main.LimboSDLActivity}
I/ActivityManager(  690): Process com.limbo.emu.main (pid 12608) has died
W/ActivityManager(  690): App Op not allow to restart app com.limbo.emu.main/102
57
W/ActivityManager(  690): Force removing ActivityRecord{18ace731 u0 com.limbo.em
u.main/com.max2idea.android.limbo.main.LimboSDLActivity t26786}: app died, no sa
ved state
I/ActivityManager(  690): Start proc com.limbo.emu.main for activity com.limbo.e
mu.main/.LimboEmuActivity: pid=12702 uid=10257 gids={50257, 9997, 3003, 1028, 10
15} abi=x86
D/NotificationChannel( 1025): package name: com.limbo.emu.main
V/Monotype(12702): SetAppTypeFace- try to flip, app = com.limbo.emu.main
I/C:/users/dev/limbo/limbo-android/jni/..//jni/SDL/src/core/android/SDL_android.
c:97(12702): JNI_OnLoad called
I/C:/users/dev/limbo/limbo-android/jni/..//jni/SDL/src/core/android/SDL_android.
c:97(12702): JNI_OnLoad called
I/C:/users/dev/limbo/limbo-android/jni/..//jni/SDL/src/core/android/SDL_android.
c:97(12702): JNI_OnLoad called
I/C:/users/dev/limbo/limbo-android/jni/..//jni/SDL/src/core/android/SDL_android.
c:97(12702): JNI_OnLoad called
I/C:/users/dev/limbo/limbo-android/jni/..//jni/limbo/vm-executor-jni.c:52(12702)
: * JNI_OnLoad called
I/ActivityManager(  690): Displayed com.limbo.emu.main/.LimboEmuActivity: +821ms

D/PowerSaverService( 3170): current package:com.limbo.emu.main;activity:com.limb
o.emu.main.LimboEmuActivity
W/LinkRimService( 1025): ---app importance: 100appProcess.processName: com.limbo
.emu.main
I/ActivityManager(  690): moveTaskToBack: TaskRecord{8de82a #26786 A=com.limbo.e
mu.main U=0 sz=1}

**Comment by a8581081** [comment] 2017-04-12 03:41
It seems indeed the permission problem, could developers create a place in the application to modified the full qemu command line, or add an option to grant su permission? Thanks

**Comment by ycavan** [comment] 2017-04-12 15:21
This is why I recommended that qemu is compiled as an android command line application.  In order to grant root, you would need to create a command shell calling su.  

Something along the lines of:

Process p;
try {
  // get root shell
  p = Runtime.getRuntime().exec("su");

  os.writeBytes("qemu and all the flags");
  os.writeBytes("exit");
  os.flush();
  try {
     p.waitFor();
     if (p.exitValue() == 255 ) {
        toastMessage("You need root to run this.");
     }
  } catch (InterruptedException e ) {
       toastMessage("You need root to run this.");
  }
} catch ( IOException e ) {
  toastMessage("You need root to run this.");
}

**Comment by limboemu** [comment] 2019-03-19 14:52
Running QEMU as root is not required, make sure you provide adequate file permissions to /dev/kvm file.
Limbo x86 Emulator for Android x86 is fully tested and works with KVM.

**Closed by limboemu** 2019-03-19 14:52 UTC
Labels: enhancement, help wanted

**Comment by stereoplegic** [comment] 2019-06-10 02:01
Is there more info on using this in x86 with KVM (I notice it's "coming soon" in the wiki)? This could be HUGE for desktop Android, especially with the ability to virtualize Win10, MacOS (via the [OSX-KVM](https://github.com/kholia/OSX-KVM) project and others), and "real Linux" as mentioned before on desktops/laptops with far more power than any phone can offer (and possibly even tricking out these alt-OSes as far as GPU passthrough on multi-card/monitor setups).

I know RemixOS is dead, and Androidx86 is far from ideal for large screens, but I just found out about this project: [PrimeOS](https://primeos.in/). It's another windowed, desktop paradigm Android like Remix, with the latest release using kernel 4.14 for older hardware and 4.19 for newer (>=2014) hardware. Seems promising.

**Comment by limboemu** [comment] 2019-06-18 08:05
The emulator supports KVM, make sure you use the latest version in this repo. It is tested successfully with Android-x86 (32bit). Also make sure you have a KVM supported kernel (Android-x86 version 5.1 ISO has KVM module compiled). I haven't tested with PrimeOS.

I'll update the wiki some day meanwhile this is a short guide:

Check if KVM is loaded from within the Android terminal:
lsmod | grep kvm

Check also if there is a device file /dev/kvm, you should provide adequate file permissions to the device file:
chmod 666 /dev/kvm

Start the emulator, create a vm, and enable KVM in the options.
Start the vm

**Comment by limboemu** [comment] 2019-06-22 11:01
Wiki updated: https://github.com/limboemu/limbo/wiki/KVM
